version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - mongo
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
    depends_on:
      - api
      - client
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - '27017:27017'
