name: Build and deploy Node.js app to Azure Web App - vici-scheduler-api-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.14.0'
      - name: npm install
        run: |
          npm install
        working-directory: ./backend
      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vici-scheduler-api-server'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B5B992D6AC9C42719E0D018A64192209 }}
          package: ./backend
